config/routes.rb
Rails.application.routes.draw do
  # get 'students/index'
  # get 'students/show'
  # get 'students/edit'
  # get 'students/new'
  resources :students
  root 'students#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
   class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params["id"])
  end

  def new
    @student = Student.new
  end

  def create
    student = Student.create(student_params)
     redirect_to students_path   
  end

  def edit
    @student = Student.find(params["id"])
  end

  def update
    @student = Student.find(params["id"])
    @student.update(student_params)
    redirect_to students_path 
  end
  def destroy
    @student = Student.find(params["id"])
    @student.destroy
    redirect_to students_path
  end

 private
 def student_params
  params.require(:student).permit(:name,:age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h2>Update a student</h3>
<%= form_with model:@student do |f| %>
<%= f.label:name%>
<%= f.text_field :name, placeholder:"Enter you name" %><br>
<%= f.label:age%>
<%= f.text_field :age , placeholder:"Enter your age" %><br>
<%= f.submit %>
<% end %>

app/views/students/index.html.erb
<h1> Students List </h1>
<table border>
<% @students.each do |std| %>
	<tr>
	<td><%= link_to std.name, student_path(std) %></td>
	<td><%= button_to 'Edit' , edit_student_path(std), method: :'get' %> </td>
	<td> <%= button_to "Remove",student_path(std),method: :'delete', data:{confirm: 'are you sure'} %></td>
	</tr>
	<% end %>
</table>
<br>
<%= link_to "Add new student", new_student_path %>

app/views/students/new.html.erb
<h2> Create a student</h3>
<%= form_with model:@student do |f| %>
<%= f.label:name%>
<%= f.text_field :name,required: true , placeholder:"Enter you name" %><br>
<%= f.label:age%>
<%= f.text_field :age ,required: true , placeholder:"Enter your age" %><br>
<%= f.submit %>
<% end %>

app/views/students/show.html.erb
<h1>Students Details</h1>
<h4>Name: <%= @student.name %><h4>
<p>Age: <%= @student.age %></p>